{application,number,
             [{applications,[kernel,stdlib,elixir,logger,decimal]},
              {description,"Convert numbers to various string formats, such as currency"},
              {modules,['Elixir.Number','Elixir.Number.Conversion',
                        'Elixir.Number.Conversion.BitString',
                        'Elixir.Number.Conversion.Decimal',
                        'Elixir.Number.Conversion.Float',
                        'Elixir.Number.Conversion.Integer',
                        'Elixir.Number.Currency','Elixir.Number.Decimal',
                        'Elixir.Number.Delimit','Elixir.Number.Human',
                        'Elixir.Number.Macros','Elixir.Number.Percentage',
                        'Elixir.Number.Phone','Elixir.Number.SI']},
              {registered,[]},
              {vsn,"1.0.3"}]}.
